import styles from "./Example.module.css";

interface ExampleData {
  html: string;
  codeHtml: string;
}

interface ExampleProps {
  data: ExampleData;
}

export function Example({ data }: ExampleProps) {
  return (
    <div className={styles.card}>
      {/* Safe: HTML is generated by unifast compiler from trusted local .md files at build time */}
      <div className={styles.preview} dangerouslySetInnerHTML={{ __html: data.html }} />
      <div className={styles.codeWrapper} dangerouslySetInnerHTML={{ __html: data.codeHtml }} />
    </div>
  );
}
